---
- hosts: localhost

  tasks:
    # "debug" is executed for all elements for which the condition "item < 5" is true
    # "when" is executed for all elements defined for the "loop"
    - name: debug loop
      debug:
        msg: "used item {{ item }}"
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item < 5

    - name: main playbook
      debug:
        msg: the next step in the main playbook
